### ISSUE TITLE
問い合わせフォームの実装

### ISSUE THREAD

**Issue by technicakidz** [Toyoshima4310/wordpress_portfolio_git#1]
### 概要/背景
現在問い合わせフォーム画面が実装されている。
実際にフォームの送信までは行えていない。

### 変更箇所
- `wp-content/plugins/` 配下の content form 7

### 完了条件
- [x] (ユーザ側)送信ボタンを押下すると確認完了画面に遷移する
- [x] (管理者側)登録したアドレス宛に内容が送信される

**Comment by technicakidz** [comment]
- サンクスページ遷移設定の参考記事
cf. https://haniwaman.com/contact-form-7-add-page/
- ajax 通信のエラー検知等設定方法
cf. https://qiita.com/konweb/items/876bf71fbba3b86bcda3

**Comment by Toyoshima4310** [comment]
フォームの実装が完了しました。
